#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

resources_dir=$PWD/request-pipeline/resources
mkdir -p $resources_dir

promises=(
    "postgresql"
    "knative-service"
    "redis"
    )

for promise in "${promises[@]}"; do
    cp $PWD/promises/${promise}/resource-request.yaml ${resources_dir}/${promise}-resource-request.yaml
done

urls=(
    "https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/slack/resource-request.yaml"
)

for url in "${urls[@]}"; do
    promise=$(basename $(dirname $url))
    curl -sL -o ${resources_dir}/${promise}-resource-request.yaml $url
done


