#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

resource_dir=$PWD/dependencies
mkdir -p ${resource_dir}

promises=(
    "deployment"
    "nginx-ingress"
)


for promise in "${promises[@]}"; do
    cat ${PWD}/promises/${promise}/promise.yaml | \
        yq eval '(select(.kind == "Promise") | .spec.destinationSelectors[0]) = { "matchLabels": { "environment": "dev" } }' > ${resource_dir}/${promise}-promise.yaml
done

marketplacePromises=(
    "https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/redis/promise.yaml"
    "https://raw.githubusercontent.com/syntasso/promise-postgresql/main/promise.yaml"
)

for promise in "${marketplacePromises[@]}"; do
    promise_name=$(basename $(dirname $promise))
    if [ "${promise_name}" == "main" ]; then
        promise_name="$(echo $promise | cut -d "/" -f 5 | cut -d "-" -f 2)"
    fi
    curl -sL "${promise}" |
        yq eval '(select(.kind == "Promise") | .spec.destinationSelectors[0]) = { "matchLabels": { "environment": "dev" } }' | \
        yq eval '.spec.workflows.resource.configure[0].spec.containers += { "name": "add-destination", "image": "ghcr.io/syntasso/kratix-marketplace/pipeline-destination-image:v0.1.0" }' \
        > ${resource_dir}/${promise_name}-promise.yaml
done

urls=(
    "https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/slack/promise.yaml"
)

for url in "${urls[@]}"; do
    promise=$(basename $(dirname $url))
    curl -sL -o ${resource_dir}/${promise}-promise.yaml $url
done
