// Code generated by counterfeiter. DO NOT EDIT.
package controllerfakes

import (
	"sync"

	"github.com/go-logr/logr"
	"github.com/syntasso/kratix/internal/controller"
	v1 "k8s.io/api/core/v1"
)

type FakeRepositoryCache struct {
	CleanupStub        func(controller.StateStore) error
	cleanupMutex       sync.RWMutex
	cleanupArgsForCall []struct {
		arg1 controller.StateStore
	}
	cleanupReturns struct {
		result1 error
	}
	cleanupReturnsOnCall map[int]struct {
		result1 error
	}
	GetRepositoryByTypeAndNameStub        func(string, string) (*controller.Repository, error)
	getRepositoryByTypeAndNameMutex       sync.RWMutex
	getRepositoryByTypeAndNameArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getRepositoryByTypeAndNameReturns struct {
		result1 *controller.Repository
		result2 error
	}
	getRepositoryByTypeAndNameReturnsOnCall map[int]struct {
		result1 *controller.Repository
		result2 error
	}
	InitRepositoryStub        func(logr.Logger, controller.StateStore, v1.Secret) (*controller.Repository, *controller.StateStoreError)
	initRepositoryMutex       sync.RWMutex
	initRepositoryArgsForCall []struct {
		arg1 logr.Logger
		arg2 controller.StateStore
		arg3 v1.Secret
	}
	initRepositoryReturns struct {
		result1 *controller.Repository
		result2 *controller.StateStoreError
	}
	initRepositoryReturnsOnCall map[int]struct {
		result1 *controller.Repository
		result2 *controller.StateStoreError
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRepositoryCache) Cleanup(arg1 controller.StateStore) error {
	fake.cleanupMutex.Lock()
	ret, specificReturn := fake.cleanupReturnsOnCall[len(fake.cleanupArgsForCall)]
	fake.cleanupArgsForCall = append(fake.cleanupArgsForCall, struct {
		arg1 controller.StateStore
	}{arg1})
	stub := fake.CleanupStub
	fakeReturns := fake.cleanupReturns
	fake.recordInvocation("Cleanup", []interface{}{arg1})
	fake.cleanupMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRepositoryCache) CleanupCallCount() int {
	fake.cleanupMutex.RLock()
	defer fake.cleanupMutex.RUnlock()
	return len(fake.cleanupArgsForCall)
}

func (fake *FakeRepositoryCache) CleanupCalls(stub func(controller.StateStore) error) {
	fake.cleanupMutex.Lock()
	defer fake.cleanupMutex.Unlock()
	fake.CleanupStub = stub
}

func (fake *FakeRepositoryCache) CleanupArgsForCall(i int) controller.StateStore {
	fake.cleanupMutex.RLock()
	defer fake.cleanupMutex.RUnlock()
	argsForCall := fake.cleanupArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRepositoryCache) CleanupReturns(result1 error) {
	fake.cleanupMutex.Lock()
	defer fake.cleanupMutex.Unlock()
	fake.CleanupStub = nil
	fake.cleanupReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepositoryCache) CleanupReturnsOnCall(i int, result1 error) {
	fake.cleanupMutex.Lock()
	defer fake.cleanupMutex.Unlock()
	fake.CleanupStub = nil
	if fake.cleanupReturnsOnCall == nil {
		fake.cleanupReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.cleanupReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepositoryCache) GetRepositoryByTypeAndName(arg1 string, arg2 string) (*controller.Repository, error) {
	fake.getRepositoryByTypeAndNameMutex.Lock()
	ret, specificReturn := fake.getRepositoryByTypeAndNameReturnsOnCall[len(fake.getRepositoryByTypeAndNameArgsForCall)]
	fake.getRepositoryByTypeAndNameArgsForCall = append(fake.getRepositoryByTypeAndNameArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.GetRepositoryByTypeAndNameStub
	fakeReturns := fake.getRepositoryByTypeAndNameReturns
	fake.recordInvocation("GetRepositoryByTypeAndName", []interface{}{arg1, arg2})
	fake.getRepositoryByTypeAndNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepositoryCache) GetRepositoryByTypeAndNameCallCount() int {
	fake.getRepositoryByTypeAndNameMutex.RLock()
	defer fake.getRepositoryByTypeAndNameMutex.RUnlock()
	return len(fake.getRepositoryByTypeAndNameArgsForCall)
}

func (fake *FakeRepositoryCache) GetRepositoryByTypeAndNameCalls(stub func(string, string) (*controller.Repository, error)) {
	fake.getRepositoryByTypeAndNameMutex.Lock()
	defer fake.getRepositoryByTypeAndNameMutex.Unlock()
	fake.GetRepositoryByTypeAndNameStub = stub
}

func (fake *FakeRepositoryCache) GetRepositoryByTypeAndNameArgsForCall(i int) (string, string) {
	fake.getRepositoryByTypeAndNameMutex.RLock()
	defer fake.getRepositoryByTypeAndNameMutex.RUnlock()
	argsForCall := fake.getRepositoryByTypeAndNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRepositoryCache) GetRepositoryByTypeAndNameReturns(result1 *controller.Repository, result2 error) {
	fake.getRepositoryByTypeAndNameMutex.Lock()
	defer fake.getRepositoryByTypeAndNameMutex.Unlock()
	fake.GetRepositoryByTypeAndNameStub = nil
	fake.getRepositoryByTypeAndNameReturns = struct {
		result1 *controller.Repository
		result2 error
	}{result1, result2}
}

func (fake *FakeRepositoryCache) GetRepositoryByTypeAndNameReturnsOnCall(i int, result1 *controller.Repository, result2 error) {
	fake.getRepositoryByTypeAndNameMutex.Lock()
	defer fake.getRepositoryByTypeAndNameMutex.Unlock()
	fake.GetRepositoryByTypeAndNameStub = nil
	if fake.getRepositoryByTypeAndNameReturnsOnCall == nil {
		fake.getRepositoryByTypeAndNameReturnsOnCall = make(map[int]struct {
			result1 *controller.Repository
			result2 error
		})
	}
	fake.getRepositoryByTypeAndNameReturnsOnCall[i] = struct {
		result1 *controller.Repository
		result2 error
	}{result1, result2}
}

func (fake *FakeRepositoryCache) InitRepository(arg1 logr.Logger, arg2 controller.StateStore, arg3 v1.Secret) (*controller.Repository, *controller.StateStoreError) {
	fake.initRepositoryMutex.Lock()
	ret, specificReturn := fake.initRepositoryReturnsOnCall[len(fake.initRepositoryArgsForCall)]
	fake.initRepositoryArgsForCall = append(fake.initRepositoryArgsForCall, struct {
		arg1 logr.Logger
		arg2 controller.StateStore
		arg3 v1.Secret
	}{arg1, arg2, arg3})
	stub := fake.InitRepositoryStub
	fakeReturns := fake.initRepositoryReturns
	fake.recordInvocation("InitRepository", []interface{}{arg1, arg2, arg3})
	fake.initRepositoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepositoryCache) InitRepositoryCallCount() int {
	fake.initRepositoryMutex.RLock()
	defer fake.initRepositoryMutex.RUnlock()
	return len(fake.initRepositoryArgsForCall)
}

func (fake *FakeRepositoryCache) InitRepositoryCalls(stub func(logr.Logger, controller.StateStore, v1.Secret) (*controller.Repository, *controller.StateStoreError)) {
	fake.initRepositoryMutex.Lock()
	defer fake.initRepositoryMutex.Unlock()
	fake.InitRepositoryStub = stub
}

func (fake *FakeRepositoryCache) InitRepositoryArgsForCall(i int) (logr.Logger, controller.StateStore, v1.Secret) {
	fake.initRepositoryMutex.RLock()
	defer fake.initRepositoryMutex.RUnlock()
	argsForCall := fake.initRepositoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRepositoryCache) InitRepositoryReturns(result1 *controller.Repository, result2 *controller.StateStoreError) {
	fake.initRepositoryMutex.Lock()
	defer fake.initRepositoryMutex.Unlock()
	fake.InitRepositoryStub = nil
	fake.initRepositoryReturns = struct {
		result1 *controller.Repository
		result2 *controller.StateStoreError
	}{result1, result2}
}

func (fake *FakeRepositoryCache) InitRepositoryReturnsOnCall(i int, result1 *controller.Repository, result2 *controller.StateStoreError) {
	fake.initRepositoryMutex.Lock()
	defer fake.initRepositoryMutex.Unlock()
	fake.InitRepositoryStub = nil
	if fake.initRepositoryReturnsOnCall == nil {
		fake.initRepositoryReturnsOnCall = make(map[int]struct {
			result1 *controller.Repository
			result2 *controller.StateStoreError
		})
	}
	fake.initRepositoryReturnsOnCall[i] = struct {
		result1 *controller.Repository
		result2 *controller.StateStoreError
	}{result1, result2}
}

func (fake *FakeRepositoryCache) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.cleanupMutex.RLock()
	defer fake.cleanupMutex.RUnlock()
	fake.getRepositoryByTypeAndNameMutex.RLock()
	defer fake.getRepositoryByTypeAndNameMutex.RUnlock()
	fake.initRepositoryMutex.RLock()
	defer fake.initRepositoryMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRepositoryCache) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ controller.RepositoryCache = new(FakeRepositoryCache)
