apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: promise-with-no-workflow
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: redis.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: redis
        plural: redis
        singular: redis
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties: {}
                  type: object
              type: object
          served: true
          storage: true
  workflows:
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: first-pipeline
          spec:
            containers:
              - image: syntasso/demo-redis-configure-pipeline:v0.1.0
                name: demo-redis-configure-pipeline
    resource: {}