apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: promise-with-deps
spec:
  destinationSelectors:
    - matchLabels:
        environment: prod
  dependencies:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: postgresoperator # was redisoperator
        namespace: default
      spec:
        replicas: 1
