apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: redis
  labels:
    kratix.io/promise-version: v1.2.0
    clashing-label: "new-promise-v2-value"
    new-promise-v2-label: "value"
  annotations:
    clashing-annotation: "new-promise-v2-value"
    new-promise-v2-annotation: "value"
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: redis.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: redis
        plural: redis
        singular: redis
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    clusterSelectors:
                      description: |
                        List of key:value pairs to use as cluster selectors when scheduling
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    size:
                      default: small
                      description: |
                        Size of this Redis deployment. If small, it deploy redis with a single replica; if large, deploy redis with 3 replicas.
                      pattern: ^(small|large)$
                      type: string
                    newConfig:
                      default: "1"
                      description: example config
                      type: string
                  type: object
              type: object
          served: true
          storage: true
  dependencies:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: updated-namespace
  destinationSelectors:
  - matchLabels:
      environment: dev
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
            namespace: default
          spec:
            containers:
              - image: syntasso/demo-redis-configure-pipeline:v1.1.0
                name: demo-redis-configure-pipeline
