# .golangci-required.yml
#
# Configuration for golangci-lint with required settings.
#
# This is a must-have set of rules to be used in precommit hooks and in CI/CD pipelines.
#
# This configuration is intended to be used as a green starting point for a set of rules
# that can be gradually tightened as the codebase matures.

version: "2"

run:
  timeout: 5m

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true

formatters:
  enable:
    - goimports

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - ginkgolinter
    - gocognit
    - gosec
    - govet
    - iface
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nolintlint
    - predeclared
    - protogetter
    - recvcheck
    - staticcheck
    - testpackage
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    cyclop:
      max-complexity: 60
    dupl:
      threshold: 100
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprint
        - fmt.Fprintln
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    funlen:
      lines: 233
      statements: 125
    gocognit:
      min-complexity: 60
    misspell:
      locale: UK
    nakedret:
      max-func-lines: 0
    nestif:
      min-complexity: 13
    nolintlint:
      require-specific: true
  exclusions:
    paths:
      - tools
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gosec
        path: '(.+)_test\.go'
      - linters:
          - gosec
          - nolintlint
          - staticcheck
        path: 'test/kubeutils/cluster\.go'
      - path: '(.+)\.go$'
        text: "comment on exported .* should be of the form .*"
      - path: '(.+)\.go$'
        text: "context.Context should be the first parameter of a function"
      - path: '(.+)\.go$'
        text: 'G401: Use of weak cryptographic primitive'
      - path: '(.+)\.go$'
        text: 'G501: Blocklisted import crypto/md5: weak cryptographic primitive'
      - path: '(.+)\.go$'
        text: 'G306: Expect WriteFile permissions to be 0600 or less'
      - path: '(.+)\.go$'
        text: 'G403: RSA keys should be at least 2048 bits'
      - path: '(.+)\.go$'
        text: 'G115: integer overflow conversion int64 -> uint64'
      - path: '(.+)\.go$'
        text: "G404: Use of weak random number generator \\(math/rand or math/rand/v2 instead of crypto/rand\\)"
      - path: '(.+)\.go$'
        text: 'G304: Potential file inclusion via variable'

severity:
  default: error
