#!/usr/bin/env bash

set -e

promise_name="$(basename "$(dirname "${PWD}")")"
pipeline_image="syntasso/demo-${promise_name}-configure-pipeline:v0.1.1"
build_cmd="docker build"
if [ "${CI:-false}" = "true" ]; then
  build_cmd="docker buildx build --load --cache-from=type=gha --cache-to=type=gha,mode=max"
fi

while [ $# -gt 0 ]; do
  case "$1" in
    build)
      ${build_cmd} \
        --tag "${pipeline_image}" \
        --platform linux/amd64 \
        "${PWD}/configure-pipeline" ;;

    load)
      kind load docker-image "${pipeline_image}" --name platform ;;

    push)
      docker push "${pipeline_image}" ;;

    rmi)
      docker rmi --force "${pipeline_image}" ;;

    pull)
      docker pull "${pipeline_image}" ;;

    *)
      echo "unknown command $1"
      exit 1
      ;;
  esac
  shift
done
