#!/usr/bin/env bash

set -e

PWD="$( cd $(dirname $0)/.. && pwd)"

internal_promises=$PWD/app-as-a-service/internal/promises
script_path=internal/scripts/pipeline-image

while [ $# -gt 0 ]; do
  case "$1" in
    build)
      ${PWD}/app-as-a-service/$script_path $1
      $internal_promises/redis/$script_path $1
      $internal_promises/knative-service/$script_path $1
      $internal_promises/postgresql/$script_path $1 ;;

    load)
      ${PWD}/app-as-a-service/$script_path $1
      $internal_promises/redis/$script_path $1
      $internal_promises/knative-service/$script_path $1
      $internal_promises/postgresql/$script_path $1 ;;

    push)
      ${PWD}/app-as-a-service/$script_path $1
      $internal_promises/redis/$script_path $1
      $internal_promises/knative-service/$script_path $1
      $internal_promises/postgresql/$script_path $1 ;;

    rmi)
      ${PWD}/app-as-a-service/$script_path $1
      $internal_promises/redis/$script_path $1
      $internal_promises/knative-service/$script_path $1
      $internal_promises/postgresql/$script_path $1 ;;

    pull)
      ${PWD}/app-as-a-service/$script_path $1
      $internal_promises/redis/$script_path $1
      $internal_promises/knative-service/$script_path $1
      $internal_promises/postgresql/$script_path $1 ;;

    *)
      echo "unknown command $1"
      exit 1
      ;;
  esac
  shift
done
