#!/usr/bin/env bash

set -e

PWD="$( cd $(dirname $0)/.. && pwd)"

if [[ -z "${LPASS_SLACK_URL}" ]]; then
  lpass ls | grep -e "demo-alerts"
  LPASS_SLACK_URL=$(lpass show 3118395568578530603 --password)
fi

${PWD}/../scripts/quick-start.sh --local-images ${PWD}/cached-images/ --recreate
${PWD}/../scripts/prepare-platform-cluster-as-worker.sh

kubectl --context kind-platform --namespace default create secret generic \
  slack-channel-hook --from-literal=url=$LPASS_SLACK_URL
