apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/component: kratix-manager
  app.kubernetes.io/instance: kratix-platform
  app.kubernetes.io/part-of: kratix

# The wc-img-config config map drives the WC_IMG env var, which is used by the promise
# controller as the last container in the workflow Pipeline pod spec.
configMapGenerator:
- envs:
  - wc-img-config.properties
  name: config

images:
- name: controller
  newName: docker.io/syntasso/kratix-platform
  newTag: dev
