apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/component: kratix-manager
  app.kubernetes.io/instance: kratix-platform
  app.kubernetes.io/part-of: kratix

patchesStrategicMerge:
- patches/wc_image_value.yaml

images:
- name: controller
  newName: docker.io/syntasso/kratix-platform
  newTag: dev
