apiVersion: platform.kratix.io/v1alpha1
kind: HealthDefinition
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k8s-health-agent
  name: healthdefinition-sample
  namespace: default
spec:
  input: |
    apiVersion: mypromise.org/v1
    kind: Psql
    metadata:
        name: mypsql
        namespace: default
    spec:
        example: fun
    status:
        bucketURL: test.com
        connectionString: psql@hostname.com
  promiseRef:
    name: psql
  promiseVersion: v2.0.0
  resourceRef:
    name: mypsql
    namespace: default
  schedule: '* * * * *'
  workflow:
    apiVersion: platform.kratix.io/v1alpha1
    kind: Pipeline
    metadata:
      name: health
    spec:
      containers:
      - image: busybox
        name: health
      rbac:
        permissions:
        - apiGroups:
          - batch
          resourceNames:
          - my-job
          resources:
          - jobs
          verbs:
          - get
