apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: paved-path-demo-promise
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: paved-path-demos.example.promise.syntasso.io
    spec:
      group: example.promise.syntasso.io
      names:
        kind: paved-path-demo
        plural: paved-path-demos
        singular: paved-path-demo
      scope: Namespaced
      versions:
        - name: v1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    name:
                      type: string
                  type: object
              type: object
          served: true
          storage: true
  dependencies:
    - apiVersion: platform.kratix.io/v1alpha1
      kind: Promise
      metadata:
        name: postgresql
        namespace: default
      spec:
        destinationSelectors:
          - matchLabels:
              environment: dev
        api:
          apiVersion: apiextensions.k8s.io/v1
          kind: CustomResourceDefinition
          metadata:
            name: postgresqls.marketplace.kratix.io
          spec:
            group: marketplace.kratix.io
            names:
              kind: postgresql
              plural: postgresqls
              singular: postgresql
            scope: Namespaced
            versions:
              - name: v1alpha1
                schema:
                  openAPIV3Schema:
                    properties:
                      spec:
                        properties:
                          dbName:
                            default: postgres
                            description: |
                              Database name. A database will be created with this name. The owner of the database will be the teamId.
                            type: string
                          env:
                            default: dev
                            description: |
                              Configures and deploys this PostgreSQL with environment specific configuration. Prod PostgreSQL are configured with backups and more resources.
                            pattern: ^(dev|prod)$
                            type: string
                          namespace:
                            default: default
                            description: |
                              Kubernetes namespace to create the Postgres cluster.
                            type: string
                          teamId:
                            default: acid
                            description: |
                              Team ID. A superuser role will be created with this name.
                            type: string
                        type: object
                    type: object
                served: true
                storage: true
        workflows:
          promise:
            configure:
              - apiVersion: platform.kratix.io/v1alpha1
                kind: Pipeline
                metadata:
                  name: promise-configure
                  namespace: default
                spec:
                  containers:
                    - image: ghcr.io/syntasso/promise-postgresql/postgresql-configure-pipeline:v0.1.0
                      name: psql-promise-pipeline
          resource:
            configure:
              - apiVersion: platform.kratix.io/v1alpha1
                kind: Pipeline
                metadata:
                  name: instance-configure
                  namespace: default
                spec:
                  containers:
                    - image: ghcr.io/syntasso/promise-postgresql/postgresql-configure-pipeline:v0.1.0
                      name: postgresql-configure-pipeline
    - apiVersion: platform.kratix.io/v1alpha1
      kind: Promise
      metadata:
        name: knative
      spec:
        destinationSelectors:
          - matchLabels:
              environment: dev
        api:
          apiVersion: apiextensions.k8s.io/v1
          kind: CustomResourceDefinition
          metadata:
            name: knatives.marketplace.kratix.io
          spec:
            group: marketplace.kratix.io
            names:
              kind: knative
              plural: knatives
              singular: knative
            scope: Namespaced
            versions:
              - name: v1alpha1
                schema:
                  openAPIV3Schema:
                    properties:
                      spec:
                        properties:
                          env:
                            default: dev
                            description: |
                              Configures and deploys this Knative with environment specific configuration.
                              Prod Knative enables application autoscaling using HPA.
                            pattern: ^(dev|prod)$
                            type: string
                        type: object
                    type: object
                served: true
                storage: true
        workflows:
          promise:
            configure:
              - apiVersion: platform.kratix.io/v1alpha1
                kind: Pipeline
                metadata:
                  name: promise-configure
                  namespace: default
                spec:
                  containers:
                    - image: ghcr.io/syntasso/kratix-marketplace/knative-configure-pipeline:v0.1.0
                      name: knative-promise-pipeline
          resource:
            configure:
              - apiVersion: platform.kratix.io/v1alpha1
                kind: Pipeline
                metadata:
                  name: instance-configure
                  namespace: default
                spec:
                  containers:
                    - image: ghcr.io/syntasso/kratix-marketplace/knative-configure-pipeline:v0.1.0
                      name: knative-configure-pipeline

  destinationSelectors:
    - matchLabels:
        environment: platform
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
            namespace: default
          spec:
            containers:
              - image: syntasso/paved-path-demo-configure-pipeline
                name: paved-path-demo-configure-pipeline
