#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

mkdir -p $PWD/request-pipeline/resources

urls=(
    "https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/postgresql/resource-request.yaml"
    "https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/slack/resource-request.yaml"
    "https://raw.githubusercontent.com/syntasso/kratix/dev/samples/knative-service/resource-request.yaml"
)

for url in "${urls[@]}"; do
    promise_name=$(basename $(dirname $url))
    curl -sL -o $PWD/request-pipeline/resources/${promise_name}-$(basename $url) $url
done