#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"


urls=(
    "https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/postgresql/promise.yaml"
    "https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/slack/promise.yaml"
    "https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/knative/promise.yaml"
    "https://raw.githubusercontent.com/syntasso/kratix/dev/samples/knative-service/promise.yaml"
)

mkdir -p ${PWD}/resources

for url in "${urls[@]}"; do
    promise_name=$(basename $(dirname $url))
    curl -sL $url | yq eval '(select(.kind == "Promise") | .spec.clusterSelector) = { "environment": "dev" }' > $PWD/resources/${promise_name}-$(basename $url)
done