apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
  name: database
  namespace: default
spec:
  # ---------------------------------
  # IMPORTANT: In this CR you will find an example of all options and possible configurations.
  # However, by default values are applied by the operator if values are not specified below.
  # ---------------------------------

  # ---------------------------------
  # ## Default Setup
  # ---------------------------------

  size: 1
  databaseMemoryLimit: "512Mi"
  databaseMemoryRequest: "128Mi"
  databaseCpuLimit: "60m"
  databaseCpu: "30m"
  databaseStorageRequest: "1Gi"

  # The imaged used in this project is from Red Hat. See more in https://docs.okd.io/latest/using_images/db_images/postgresql.html
  image: "centos/postgresql-96-centos7"

  # Environment Variables
  # ---------------------------------
  # Following are the values which will be used as the key label for the environment variable of the database image.
  # NOTES:
  # - They need to be as the values expected by the image used
  # - If you are using the optional setup to allow the operator looking for this value in a ConfigMap pre-existent then it will look for these keys by default
  # ---------------------------------
  databaseNameKeyEnvVar: "POSTGRESQL_DATABASE"
  databasePasswordKeyEnvVar: "POSTGRESQL_PASSWORD"
  databaseUserKeyEnvVar: "POSTGRESQL_USER"

  # The following values will be used fill the env variables. (Optional)
  # They will be not required if you are using the configMap setup
  # ---------------------------------
  databaseName: "example"
  databasePassword: "postgres"
  databaseUser: "postgres"

  # ---------------------------------
  # ## Customizations Options
  # ---------------------------------

  # Database Container
  # ---------------------------------
  # Name which will be used to create the container where the database will be running

  # containerName: "database"
  # databasePort: 5432

  # Use the following spec if you would like to define the image pull policy
  # containerImagePullPolicy: "IfNotPresent"

  # Get Values from ConfigMap
  # ---------------------------------
  # NOTE: It is very useful if you would like to centralize and share this information with your solutions

  # The following attribute allows you tell for the operator that it should look for the data to create the env vars is some
  # ConfigMap which pre-exist in the cluster
  # configMapName: "cfgmap-name"

  # The following specs allow you customize the name of the keys which the operator should look for the env vars in the configMap.
  # configMapDatabaseNameKey: "POSTGRESQL_DATABASE"
  # configMapDatabasePasswordKey: "POSTGRESQL_PASSWORD"
  # configMapDatabaseUserKey: "POSTGRESQL_USER"

  # The following allow you customize the name of the Storage Class that should be used
  # databaseStorageClassName: "standard"
