#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

mkdir -p $PWD/request-pipeline/resources


cat <<EOF > $PWD/request-pipeline/resources/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: TBDNAMESPACE
EOF

cat <<EOF > $PWD/request-pipeline/resources/knative-serving.yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: TBDNAME
  namespace: TBDNAMESPACE
spec:
  ingress:
    kourier:
      enabled: true
  config:
    domain:
      "local.gd": ""
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
EOF