#!/usr/bin/env bash

dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

root=$(cd $dir/../.. && pwd)

$root/scripts/quick-start.sh --recreate --third-cluster --local 

kubectl --context kind-platform label destination worker target=worker-1
kubectl --context kind-platform label destination worker-2 target=worker-2