#!/usr/bin/env sh

set -euxo pipefail

status_file=/work-creator-files/metadata/status.yaml
# timestamp is RFC3339
export conditions="message: Pipeline completed
lastTransitionTime: \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
status: \"True\"
type: PipelineCompleted
reason: PipelineExecutedSuccessfully
"

# If Resource doesn't have status.message field...
export status_values="message: Resource requested"
if [ -f "$status_file" ]; then
	export status_values="$(cat $status_file)"
fi

yq -n '.status = env(status_values)' |  yq '.status.conditions[0] = env(conditions)' > status.yaml
# TODO: Should we check if printer fields values exist?
#       Default behaviour is to just be empty (not error)

kubectl patch $RR_KIND/$RR_NAME --namespace $RR_NAMESPACE --type merge --patch-file status.yaml --subresource status
