#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

mkdir -p $PWD/configure-pipeline/dependencies/instance

instance_urls=(
    "https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/minimal-postgres-manifest.yaml"
)

for url in "${instance_urls[@]}"; do
    curl -sL -o $PWD/configure-pipeline/dependencies/instance/$(basename $url) $url
done
