#!/usr/bin/env bash
set -e

test_promise() {
  kubectl get crds postgresqls.acid.zalan.do
  kubectl wait --for=condition=Available --timeout=5s deployment/postgres-operator
}

test_resource_request() {
  kubectl wait --for=condition=ready --timeout=5s pod/acid-example-postgresql-0
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
