#!/usr/bin/env sh

set -x

# Read current values from the provided resource request
export name="$(yq eval '.spec.name' /kratix/input/object.yaml)"
export image="$(yq eval '.spec.image' /kratix/input/object.yaml)"
export db_driver="$(yq eval '.spec.dbDriver' /kratix/input/object.yaml)"
export db_name="${name}db"


if [ $db_driver = 'postgres' ]; then
  # set values that work with sample app at https://github.com/syntasso/sample-golang-app
  cat /tmp/transfer/postgresql-resource-request.yaml \
    | yq eval '.metadata.name = env(name)
      | .spec.dbName = env(db_name)' \
    > /kratix/output/postgresql-resource-request.yaml
fi

cat /tmp/transfer/deployment-resource-request.yaml \
  | yq eval '.metadata.name = env(name) | .spec.image = env(image)' \
  > /kratix/output/deployment-resource-request.yaml
