# Adding comment before first yaml document divider as this can fail to decode as yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: messaging
