apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: worker-1
  labels:
    environment: dev
spec:
  path: worker-1
  stateStoreRef:
    name: default
    kind: BucketStateStore
