apiVersion: platform.kratix.io/v1alpha1
kind: BucketStateStore
metadata:
  name: default
spec:
  endpoint: bucket.seaweedfs.svc.cluster.local
  insecure: true
  bucketName: kratix
  authMethod: accessKey
  secretRef:
    name: bucket-credentials
    namespace: default
