// Code generated by MockGen. DO NOT EDIT.
// Source: git.go
//
// Generated by this command:
//
//	mockgen -source=git.go -destination=mocks/mock_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
