#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"


urls=(
    "https://github.com/knative/operator/releases/download/knative-v1.8.2/operator.yaml"
)

mkdir -p ${PWD}/resources

for url in "${urls[@]}"; do
    promise_name=$(basename $(dirname $url))
    curl -sL $url \
    | yq 'del(.data._example)' \
     > $PWD/resources/${promise_name}-$(basename $url)
done

curl -sL https://github.com/knative/serving/releases/download/knative-v1.8.3/serving-crds.yaml | \
    yq 'select(.metadata.name == "services.serving.knative.dev")' > $PWD/resources/serving-crds.yaml