---
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: promise-name
  namespace: default
spec:
  dependencies:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: dep-namespace
