---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-credentials
  namespace: flux-system
type: Opaque
data:
  username: Z2l0ZWFfYWRtaW4=
  password: cjhzQThDUEhEOSFidDZk
  caFile: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdCakNDQSs2Z0F3SUJBZ0lVZTlSTW9hbWlORURqWERqam9WdDBrczZKVXFFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZWXhDekFKQmdOVkJBWVRBbGhZTVJJd0VBWURWUVFJREFsVGRHRjBaVTVoYldVeEVUQVBCZ05WQkFjTQpDRU5wZEhsT1lXMWxNUlF3RWdZRFZRUUtEQXREYjIxd1lXNTVUbUZ0WlRFYk1Ca0dBMVVFQ3d3U1EyOXRjR0Z1CmVWTmxZM1JwYjI1T1lXMWxNUjB3R3dZRFZRUUREQlJEYjIxdGIyNU9ZVzFsVDNKSWIzTjBibUZ0WlRBZUZ3MHkKTXpFeU1URXhNVFV6TURWYUZ3MHpNekV5TURneE1UVXpNRFZhTUlHR01Rc3dDUVlEVlFRR0V3SllXREVTTUJBRwpBMVVFQ0F3SlUzUmhkR1ZPWVcxbE1SRXdEd1lEVlFRSERBaERhWFI1VG1GdFpURVVNQklHQTFVRUNnd0xRMjl0CmNHRnVlVTVoYldVeEd6QVpCZ05WQkFzTUVrTnZiWEJoYm5sVFpXTjBhVzl1VG1GdFpURWRNQnNHQTFVRUF3d1UKUTI5dGJXOXVUbUZ0WlU5eVNHOXpkRzVoYldVd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJSwpBb0lDQVFDdC9KaXJrelB6cFBKUVdkOEJsTGIzU2dWU1B2L1RjZFdSQXFBaUlpNTBkMEwvN2gxQjkzejJuaTVNCjdyYkRPY3RmU2kyb2FCTG9uYzNmOGJEOExwZjNjT2lNamJkVmRZNCtBN3FjZVU1VURZdXdYK29hZVhNS2d3MC8KT29rbFI5eVFQc0hFU25wa0NwVmFQVm9sN2czeThUc3NnbFVnQTBJRjY4dnlGRk9iZ3Jja3dVOGUyeElEU1hzZApYbGF6a1RmV0oyb3d6aWhTblR1REtyUGc3REZWdHNHcGlvdExDTUVtQmhzUHl4NTl1ZTFTdFFvanhjNndnWHFtCjFmZE1UK25KZW9pUVJ1SURpQ0lKYUhuK0ZvV2cyQi90L3EwbGxvMllSSlFJY1VnYisyWERFYzhXY0dXblZTaXQKQzd1bjNETzlZZXFRN0hFMFJEMFpQWWRUcUE3ZzB1bE5mUXg5M1gwZmxDTEJlVzZPa0drc014QnpBaXBMY28xaAp4ekdxcWE0ZnlqQUx5T2JLVFFLTXM5dnRjRUZ6RzgwSmROL3ByUGx3Ukp1VFpHOWRuS1loR1V2aEg0d3NhVXlFCjFHNkFZV0VuZC9XaGVicTVRSkFZWFRia1piUm5lUEhrMTFnZlcxSnpPN2VESUd4Y2s2VUNUZlJmRzZ4bDAwSDYKV3d1S1lDcktMSitIblYrdml6YTVGdjJ1ODBSRVBOSjJKaXZ4WC9tLzExeGRwNkkyYUZGblF5VFJiL1lsY082TgpEMWsrNFdYV1drWjZXMGRIVGMzYzdlRXlhV0FQc0YybWNsSDAwNEp6NjNNYzhONDkzdUZ4eWp5blk1SVR6UzZ6CjdTY1dtR2xlbEJSZHJHVE5mSU9SV0UzMzI3LzV5bFJoM2YzNk1vQWdVSnZZT2NTNkRRSURBUUFCbzJvd2FEQWQKQmdOVkhRNEVGZ1FVb25ZTzA4WlgwTHcrdEZBVmlCYk5mbzdwREQ0d0h3WURWUjBqQkJnd0ZvQVVvbllPMDhaWAowTHcrdEZBVmlCYk5mbzdwREQ0d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBVkJnTlZIUkVFRGpBTWh3U3NFZ0FECmh3U3NFZ0FDTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFBZU5scTBGRlN1eTQ3aW1wQzlCWE5YVm5xcENMTmsKcHdmK3NBN2ttOGtwb1Z4VTFEOHA0WWRYZXh5ZHhsV3ZlNWsyZWExN2ZSVGQzZnlnaGdQcU04bW1FamtlRXFaRgpIRnpGYVpJQ2YrM2gxV29HSm15a3VjRTRnMzUvMk83cTgwMUl1amVYMCtsTU8vMHhuMXQxSVRWby9aOUxxY0dFCjd4MTEwMnByOE8ydEFqaVJKMm1CbUg4Qmp1SlhPd212bVUzbmJiS0FuYkxtZVRqQ1VhOUlhcU9OOXJGUW9yYWIKQUd6ZGZkNjMrcDY3NURZWS96WGh5dTJCbDV6aitpRFZKUGx4K0FNei9KcmNWNHVBUTkvbUZMVjVNNUVCbEFvdgo3aGNOSXc2UDdnV1JYWjJhaDZqa3FjeXRwcytXTGcrVDAxZy9JSlFyazlrZHMrN2piNzFvaE9VVzMweDlkMHpaCkpiRk9qSjdzYWh6Vmhub04weTNhZ3g2Zk44RGpKYmdYSjFlUFNTNzdIVXBnYy83anBCZDBhK3FONm1SandIT2MKbkZmcWVjeWtqb3dSSXNFMm0xakViL2NXZlUyZ05ERzI2SC8rd0dBSWQ4RkthQldkTlMvSUZRQzJPbTNxQndMTgp5ZFIycVM1aDduRG5pZlVabGFvdmFkTzhORWU0dExuNHhraGRpUHExdXZHbHI2V2I3ZUlWRDg3dnV5ekVGNmw2Cm5EL3dvOE9xV24xaDV0NDBRQUJtajlYbVBKeGR5a1VIM0Z5RDIyV283NE5SZ2Z0NkFJNHVnM3A2SFhVUGM0eFkKTjVDNUhnTGpSRldNWVFialZBenFwdzJMSnJUWWVUakh6TUdvVXBXN296azNrSno0WTMra3hpUFJGYVIzMHR3NgpCeGRsL25oYkRQOXZxZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kratix-workload-resources
  namespace: flux-system
spec:
  interval: 5s
  url: https://172.18.0.2:31333/gitea_admin/kratix
  ref:
    branch: main
  secretRef:
    name: gitea-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kratix-workload-resources
  namespace: flux-system
spec:
  interval: 3s
  dependsOn:
    - name: kratix-workload-dependencies
  sourceRef:
    kind: GitRepository
    name: kratix-workload-resources
  path: "worker-1/resources/"
  prune: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kratix-workload-dependencies
  namespace: flux-system
spec:
  interval: 5s
  url: https://172.18.0.2:31333/gitea_admin/kratix
  ref:
    branch: main
  secretRef:
    name: gitea-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kratix-workload-dependencies
  namespace: flux-system
spec:
  interval: 8s
  sourceRef:
    kind: GitRepository
    name: kratix-workload-dependencies
  path: "worker-1/dependencies/"
  prune: true
