config:
  path: worker-1
  namespace: kratix-worker-config
  secretRef:
    name: bucket-credentials
    values:
      accesskey: a3JhdGl4YWRtaW4=
      secretkey: a3JhdGl4YWRtaW4=
  bucket:
    insecure: true
    endpoint: 172.18.0.2:31337
    bucket: kratix

additionalResources:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: kratix-worker-config
