#!/usr/bin/env sh

set -x

# Read current values from the provided resource request
export name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"
export size="$(yq eval '.spec.size' /kratix/input/object.yaml)"

cluster_selectors="$(yq eval '.spec.clusterSelectors // ""' /kratix/input/object.yaml)"
if [ -n "$cluster_selectors" ]; then
  cat > /kratix/metadata/scheduling.yaml <<EOF
- target:
    matchLabels:
      $cluster_selectors
EOF
fi

# default small size
export replicas=1

if [ $size = large ]; then
  replicas=3
fi

# Replace defaults with user provided values
cat /tmp/transfer/redis-instance.yaml |  \
  yq eval '.metadata.name = env(name)' | \
  yq eval '.spec.redis.replicas = env(replicas)' | \
  yq eval '.spec.sentinel.replicas = env(replicas)' - \
  > /kratix/output/redis-instance.yaml
