#!/usr/bin/env bash

ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )

set -eu

cd $ROOT

source "$ROOT/scripts/utils.sh"
export VERSION="$(commit_sha)"
export DOCKER_BUILDKIT=1

docker run -it --rm --privileged tonistiigi/binfmt --install all

case "$1" in
    kratix)
        # Kratix Platform image
        make docker-build-and-push
        ;;
    work-creator)
        # Work Creator image
        make work-creator-docker-build-and-push
        ;;
    samples)
        # Build workshop images
        docker build --platform linux/amd64 --tag syntasso/paved-path-demo-request-pipeline \
            --file samples/paved-path-demo/request-pipeline-image/Dockerfile \
            samples/paved-path-demo/request-pipeline-image

        docker push syntasso/paved-path-demo-request-pipeline
        ;;
    *)
        echo "unknown image: $1"
        exit 1
        ;;
esac
