#!/usr/bin/env bash

ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )

set -eu

cd $ROOT

source "$ROOT/scripts/utils.sh"
export VERSION="${VERSION:-$(commit_sha)}"
export DOCKER_BUILDKIT=1

docker run -it --rm --privileged tonistiigi/binfmt --install all

case "$1" in
    kratix)
        # Kratix Platform image
        make docker-build-and-push
        ;;
    work-creator)
        # Work Creator image
        make build-and-push-work-creator
        ;;
    *)
        echo "unknown image: $1"
        exit 1
        ;;
esac
