#!/usr/bin/env bash

ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )
source "${ROOT}/scripts/utils.sh"

set -euo pipefail
cd $ROOT

CONTEXT=""
WORKER_STATESTORE_TYPE=${WORKER_STATESTORE_TYPE:-BucketStateStore}
KUSTOMIZATION_NAME=""
GITOPS_PROVIDER="flux"

usage() {
    echo -e "Usage: ${BASH_SOURCE[0]} [--help] [--context=""] [--path=""] [--git]"
    echo ""
    echo -e "\t--help, -h,\t Prints this message"
    echo -e "\t--context='', -c,\t Required. The Kubernetes context where to install FluxCD onto."
    echo -e "\t--path='', -b,\t The Repository name, must match the name used when registering the destination. Defaults to context."
    echo -e "\t--git, -g,\t Reads from local Gitea installation (default: Read from local MinIO installation)"
    echo -e "\t--kustomization-name, -k,\t Name of the Flux Kustomizations"
    echo -e "\t--gitops-provider, -p,\t Gitops provider, either flux or argo. Defauls to flux"
    exit "${1:-0}"
}

load_options() {
    for arg in "$@"; do
      shift
      case "$arg" in
        '--help')                       set -- "$@" '-h'   ;;
        '--context')                    set -- "$@" '-c'   ;;
        '--path')                       set -- "$@" '-b'   ;;
        '--kustomization-name')         set -- "$@" '-k'   ;;
        '--gitops-provider')            set -- "$@" '-p'   ;;
        '--git')                        set -- "$@" '-g'   ;;
        *)                              set -- "$@" "$arg" ;;
      esac
    done

    OPTIND=1
    while getopts "hc:gb:k:p:" opt
    do
      case "$opt" in
        'h') usage ;;
        'c') CONTEXT=$OPTARG ;;
        'g') WORKER_STATESTORE_TYPE=GitStateStore ;;
        'b') BUCKET_PATH=$OPTARG ;;
        'k') KUSTOMIZATION_NAME=$OPTARG ;;
        'p') GITOPS_PROVIDER=$OPTARG ;;
        *) usage 1 ;;
      esac
    done
    shift $(expr $OPTIND - 1)

    # Exit if name is not set
    if [ -z "${CONTEXT}" ]; then
        usage
        exit 1
    fi
    BUCKET_PATH="${BUCKET_PATH:-"$CONTEXT"}"
}

patch_kind_networking() {
    local file_name=$1
    if [[ "${CONTEXT}" =~ ^kind-.* ]]; then
        PLATFORM_DESTINATION_IP=$(docker inspect platform-control-plane | yq ".[0].NetworkSettings.Networks.kind.IPAddress")
        sed "s/172.18.0.2/${PLATFORM_DESTINATION_IP}/g" ${file_name}
    else
        cat "${file_name}"
    fi
}

patch_name() {
    local name="$(echo "${CONTEXT}" | cut -d "-" -f 2)"
    if [[ ! $KUSTOMIZATION_NAME == "" ]]; then
        name=$KUSTOMIZATION_NAME
    fi

    sed "s/worker-1/${BUCKET_PATH}/g" |
        sed "s/kratix-workload-dependencies/kratix-${name}-dependencies/g" |
        sed "s/kratix-workload-resources/kratix-${name}-resources/g"
}

install_flux_gitops() {
    CONTEXT="${CONTEXT:-$1}"
    BUCKET_PATH="${BUCKET_PATH:-$2}"
    resource_file=${ROOT}/hack/destination/gitops-tk-resources.yaml
    if [ ${WORKER_STATESTORE_TYPE} = "GitStateStore" ]; then
        resource_file=${ROOT}/hack/destination/gitops-tk-resources-git.yaml;
        copy_gitea_credentials kind-platform ${CONTEXT} flux-system
    fi

    # install flux crds
    kubectl --context "${CONTEXT}" apply --filename ${ROOT}/hack/destination/gitops-tk-install.yaml

    patch_kind_networking $resource_file | patch_name | kubectl --context "${CONTEXT}" apply --filename -
}

patch_argo_secret() {
    local argo_password=$(kubectl --context kind-platform get secret  gitea-credentials -n gitea -o yaml | yq .data.password | base64 -d)
    sed "s/PASSWORD/${argo_password}/g"
}

install_argocd_gitops() {
    if [ ${WORKER_STATESTORE_TYPE} != "GitStateStore" ]; then
        echo "only Git (--git) state store is supported for ArgoCD"
        exit 1
    fi

    kubectl --context "${CONTEXT}" create namespace argocd
    kubectl --namespace argocd --context "${CONTEXT}" apply --filename https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v2.13.3/manifests/install.yaml
    kubectl --context "${CONTEXT}" wait --namespace argocd --for=condition=ready --timeout=300s pods --all

    resource_file=${ROOT}/hack/destination/gitops-argo-resources-git.yaml
    patch_kind_networking $resource_file | patch_name | patch_argo_secret | kubectl --context "${CONTEXT}" apply --filename -
}

main() {
    load_options $@
    export CONTEXT="${CONTEXT:-$1}"
    export BUCKET_PATH="${BUCKET_PATH:-$2}"
    if [ ${GITOPS_PROVIDER} = "flux" ]; then
        install_flux_gitops
        exit 0
    fi

    if [ ${GITOPS_PROVIDER} = "argo" ]; then
        install_argocd_gitops
        exit 0
    fi

    echo "Unknown GitOps provider: ${GITOPS_PROVIDER}"
    exit 1
}

if [ "$0" = "${BASH_SOURCE[0]}" ]; then
    main $@
fi
