#!/usr/bin/env bash

set -eux

# ensure we are on the latest main
git pull origin main

latest_tag="latest"
current_commit=${CIRCLE_SHA1:-$(git rev-parse HEAD)}

commit_list=$(git rev-list "$latest_tag".."$current_commit")

# Check if the commit list is not empty
if [ -n "$commit_list" ]; then
    echo "Current commit is ahead of the previous tag; pushing a new tag"
    git tag -a $latest_tag -m "${latest_tag}" --force
    git push origin $latest_tag --force
else
    echo "Current commit is not ahead of the previous tag; not pushing a new tag"
fi
