#!/usr/bin/env sh

set -x

# Read current values from the provided resource request
export name="$(yq eval '.spec.name' /input/object.yaml)"
export image="$(yq eval '.spec.image' /input/object.yaml)"
export db_driver="$(yq eval '.spec.dbDriver' /input/object.yaml)"
export contains_cc="$(yq eval '.spec.containsCreditCardData' /input/object.yaml)"
export db_name="${name}db"


[[ $contains_cc = 'true' ]] && export clusterLabels="{pci: true}" || export clusterLabels="{}"

if [ $db_driver = 'postgres' ]; then
  # set values that work with sample app at https://github.com/syntasso/sample-golang-app
  cat /tmp/transfer/postgresql-resource-request.yaml \
    | yq eval '.metadata.name = env(name)
      | .spec.dbName = env(db_name)
      | .spec.clusterSelectors = env(clusterLabels)' \
    > /output/postgresql-resource-request.yaml
fi

cat /tmp/transfer/redis-resource-request.yaml \
  | yq eval '.metadata.name = env(name)
  | .spec.clusterSelectors = env(clusterLabels)' \
  > /output/redis-resource-request.yaml

export message="Deployping app: ${name}"
if $contains_cc ; then
  cat /tmp/transfer/slack-resource-request.yaml \
    | yq eval '.metadata.name = env(name) | .spec.message = "Deploying app: " + env(name) + " to pci-secure environment"' \
    > /output/slack-resource-request.yaml
else
  cat /tmp/transfer/slack-resource-request.yaml \
    | yq eval '.metadata.name = env(name) | .spec.message = "Deploying app: " + env(name)' \
    > /output/slack-resource-request.yaml
fi

cat /tmp/transfer/deployment-resource-request.yaml \
  | yq eval '.metadata.name = env(name)
  | .spec.image = env(image)
  | .spec.clusterSelectors = env(clusterLabels)
  | .spec.containsCreditCardData = env(contains_cc)' \
  > /output/deployment-resource-request.yaml
