#!/usr/bin/env sh

set -x

# Read current values from the provided resource request
export name="$(yq eval '.spec.name' /input/object.yaml)"
export image="$(yq eval '.spec.image' /input/object.yaml)"
export db_driver="$(yq eval '.spec.dbDriver' /input/object.yaml)"
export contains_cc="$(yq eval '.spec.containsCreditCardData' /input/object.yaml)"
export db_name="${name}db"


[[ $contains_cc = 'true' ]] && export clusterLabels="{pci: true}" || export clusterLabels="{}"

if [ $db_driver = 'postgres' ]; then
  # set values that work with sample app at https://github.com/syntasso/sample-golang-app
  cat /tmp/transfer/postgresql-resource-request.yaml \
    | yq eval '.metadata.name = env(name)
      | .spec.dbName = env(db_name)
      | .spec.clusterSelectors = env(clusterLabels)' \
    > /output/postgresql-resource-request.yaml
fi

cat /tmp/transfer/redis-resource-request.yaml \
  | yq eval '.metadata.name = env(name)' \
  > /output/redis-resource-request.yaml

cat /tmp/transfer/knative-service-resource-request.yaml \
  | yq eval '.metadata.name = env(name)
   | .spec.name = env(name)
   | .spec.image = env(image)
   | .spec.database.host = "acid-" + env(name) + "-postgresql.default.svc.cluster.local"
   | .spec.database.name = env(db_name)
   | .spec.database.secretKeyRef = "postgres.acid-" + env(name) + "-postgresql.credentials.postgresql.acid.zalan.do"' \
  > /output/knative-service-resource-request.yaml

cat /tmp/transfer/slack-resource-request.yaml \
  | yq eval '.metadata.name = env(name) | .spec.message = "Deploying app: " + env(name)' \
  > /output/slack-resource-request.yaml
