#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

resource_dir=$PWD/dependencies
mkdir -p ${resource_dir}

promises=(
    "postgresql"
    "nginx-ingress"
    )


for promise in "${promises[@]}"; do
    cat ${PWD}/promises/${promise}/promise.yaml | \
        yq eval '(select(.kind == "Promise") | .spec.destinationSelectors[0]) = {"matchLabels": {"environment": "dev"}}' > ${resource_dir}/${promise}-promise.yaml
done

