#!/usr/bin/env bash

set -e

pipeline_image="syntasso/demo-easy-app-configure-pipeline:v0.1.1"
nginx_pipeline="syntasso/demo-nginx-configure-pipeline:v0.1.1"
postgres_pipeline="syntasso/demo-postgresql-configure-pipeline:v0.1.1"
root="$( cd $(dirname $0)/.. && pwd)"
build_cmd="docker build"
if [ "${CI:-false}" = "true" ] && [ "${GITHUB_ACTIONS:-false}" = "true" ] && docker buildx version >/dev/null 2>&1; then
  build_cmd="docker buildx build --load --cache-from=type=local,src=${BUILDKIT_CACHE_DIR:-cache-mount} --cache-to=type=local,dest=${BUILDKIT_CACHE_DIR:-cache-mount},mode=max"
fi

while [ $# -gt 0 ]; do
  case "$1" in
    build)
      ${build_cmd} \
        --tag "${pipeline_image}" \
        --platform linux/amd64 \
        "${root}/configure-pipeline"

      ${build_cmd} \
        --tag "${nginx_pipeline}" \
        --platform linux/amd64 \
        "${root}/promises/nginx-ingress/internal/configure-pipeline"

      ${build_cmd} \
        --tag "${postgres_pipeline}" \
        --platform linux/amd64 \
        "${root}/promises/postgresql/internal/configure-pipeline" ;;

    load)
      kind load docker-image "${pipeline_image}" --name platform
      kind load docker-image "${nginx_pipeline}" --name platform
      kind load docker-image "${postgres_pipeline}" --name platform ;;

    push)
      docker push "${pipeline_image}"
      docker push "${nginx_pipeline}"
      docker push "${postgres_pipeline}" ;;

    rmi)
      docker rmi --force "${pipeline_image}"
      docker rmi --force "${postgres_image}"
      docker rmi --force "${nginx_pipeline}" ;;

    pull)
      docker pull "${pipeline_image}"
      docker pull "${postgres_image}"
      docker pull "${nginx_pipeline}" ;;

    *)
      echo "unknown command $1"
      exit 1
      ;;
  esac
  shift
done
