apiVersion: platform.kratix.syntasso.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: ha-postgres-promise
spec:
  crd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: postgreses.example.promise.syntasso.io
    spec:
      group: example.promise.syntasso.io
      names:
        kind: postgres
        plural: postgreses
        singular: postgres
      scope: Namespaced
      versions:
      - name: v1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  preparedDatabases:
                    additionalProperties:
                      properties:
                        defaultUsers:
                          type: boolean
                        extensions:
                          additionalProperties:
                            type: string
                          type: object
                        schemas:
                          additionalProperties:
                            properties:
                              defaultRoles:
                                type: boolean
                              defaultUsers:
                                type: boolean
                            type: object
                          type: object
                      type: object
                    type: object
                type: object
            type: object
        served: true
        storage: true
  requestPipeline:
  - syntasso/postgres-request-pipeline
  workerResources:
  - apiVersion: v1
    data:
      api_port: "8080"
      aws_region: eu-central-1
      cluster_domain: cluster.local
      cluster_history_entries: "1000"
      cluster_labels: application:spilo
      cluster_name_label: cluster-name
      connection_pooler_image: registry.opensource.zalan.do/acid/pgbouncer:master-16
      db_hosted_zone: db.example.com
      debug_logging: "true"
      docker_image: registry.opensource.zalan.do/acid/spilo-13:2.0-p7
      enable_ebs_gp3_migration: "false"
      enable_master_load_balancer: "false"
      enable_pgversion_env_var: "true"
      enable_replica_load_balancer: "false"
      enable_spilo_wal_path_compat: "true"
      enable_team_member_deprecation: "false"
      enable_teams_api: "false"
      external_traffic_policy: Cluster
      logical_backup_docker_image: registry.opensource.zalan.do/acid/logical-backup:v1.6.3
      logical_backup_job_prefix: logical-backup-
      logical_backup_provider: s3
      logical_backup_s3_bucket: my-bucket-url
      logical_backup_s3_sse: AES256
      logical_backup_schedule: 30 00 * * *
      major_version_upgrade_mode: manual
      master_dns_name_format: '{cluster}.{team}.{hostedzone}'
      pdb_name_format: postgres-{cluster}-pdb
      pod_deletion_wait_timeout: 10m
      pod_label_wait_timeout: 10m
      pod_management_policy: ordered_ready
      pod_role_label: spilo-role
      pod_service_account_name: postgres-pod
      pod_terminate_grace_period: 5m
      ready_wait_interval: 3s
      ready_wait_timeout: 30s
      repair_period: 5m
      replica_dns_name_format: '{cluster}-repl.{team}.{hostedzone}'
      replication_username: standby
      resource_check_interval: 3s
      resource_check_timeout: 10m
      resync_period: 30m
      ring_log_lines: "100"
      role_deletion_suffix: _deleted
      secret_name_template: '{username}.{cluster}.credentials'
      spilo_allow_privilege_escalation: "true"
      spilo_privileged: "false"
      storage_resize_mode: pvc
      super_username: postgres
      watched_namespace: '*'
      workers: "8"
    kind: ConfigMap
    metadata:
      name: postgres-operator
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: postgres-operator
      namespace: default
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: postgres-operator
    rules:
    - apiGroups:
      - acid.zalan.do
      resources:
      - postgresqls
      - postgresqls/status
      - operatorconfigurations
      verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - acid.zalan.do
      resources:
      - postgresteams
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - apiextensions.k8s.io
      resources:
      - customresourcedefinitions
      verbs:
      - create
      - get
      - patch
      - update
    - apiGroups:
      - ""
      resources:
      - configmaps
      verbs:
      - get
    - apiGroups:
      - ""
      resources:
      - events
      verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - endpoints
      verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - create
      - delete
      - get
      - update
    - apiGroups:
      - ""
      resources:
      - nodes
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - persistentvolumeclaims
      verbs:
      - delete
      - get
      - list
      - patch
      - update
    - apiGroups:
      - ""
      resources:
      - persistentvolumes
      verbs:
      - get
      - list
      - update
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - pods/exec
      verbs:
      - create
    - apiGroups:
      - ""
      resources:
      - services
      verbs:
      - create
      - delete
      - get
      - patch
      - update
    - apiGroups:
      - apps
      resources:
      - statefulsets
      - deployments
      verbs:
      - create
      - delete
      - get
      - list
      - patch
    - apiGroups:
      - batch
      resources:
      - cronjobs
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
    - apiGroups:
      - ""
      resources:
      - namespaces
      verbs:
      - get
    - apiGroups:
      - policy
      resources:
      - poddisruptionbudgets
      verbs:
      - create
      - delete
      - get
    - apiGroups:
      - ""
      resources:
      - serviceaccounts
      verbs:
      - get
      - create
    - apiGroups:
      - rbac.authorization.k8s.io
      resources:
      - rolebindings
      verbs:
      - get
      - create
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: postgres-operator
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: postgres-operator
    subjects:
    - kind: ServiceAccount
      name: postgres-operator
      namespace: default
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: postgres-pod
    rules:
    - apiGroups:
      - ""
      resources:
      - endpoints
      verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - services
      verbs:
      - create
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        application: postgres-operator
      name: postgres-operator
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: postgres-operator
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: postgres-operator
        spec:
          containers:
          - env:
            - name: CONFIG_MAP_NAME
              value: postgres-operator
            image: registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
            imagePullPolicy: IfNotPresent
            name: postgres-operator
            resources:
              limits:
                cpu: 500m
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 250Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
          serviceAccountName: postgres-operator
status: {}

