---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: Bucket
metadata:
  name: DESTINATION_NAME-workload-dependencies
  namespace: flux-system
spec:
  interval: 10s
  provider: generic
  bucketName: DESTINATION_NAME-kratix-dependencies
  endpoint: ENDPOINT
  insecure: true
  secretRef:
    name: minio-credentials
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: Bucket
metadata:
  name: DESTINATION_NAME-workload-resources
  namespace: flux-system
spec:
  interval: 10s
  provider: generic
  bucketName: DESTINATION_NAME-kratix-resources
  endpoint: ENDPOINT
  insecure: true
  secretRef:
    name: minio-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: flux-system
type: Opaque
data:
  accesskey: bWluaW9hZG1pbg==
  secretkey: bWluaW9hZG1pbg==
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: DESTINATION_NAME-workload-resources
  namespace: flux-system
spec:
  interval: 3s
  prune: true
  dependsOn:
    - name: DESTINATION_NAME-workload-dependencies
  sourceRef:
    kind: Bucket
    name: DESTINATION_NAME-workload-resources
  validation: client
  path: PATH
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: DESTINATION_NAME-workload-dependencies
  namespace: flux-system
spec:
  interval: 8s
  prune: true
  sourceRef:
    kind: Bucket
    name: DESTINATION_NAME-workload-dependencies
  validation: client
  path: PATH
