// Code generated by counterfeiter. DO NOT EDIT.
package writersfakes

import (
	"sync"

	"github.com/syntasso/kratix/lib/writers"
)

type FakeBatchFileRemover struct {
	RemoveFilesStub        func(...string) error
	removeFilesMutex       sync.RWMutex
	removeFilesArgsForCall []struct {
		arg1 []string
	}
	removeFilesReturns struct {
		result1 error
	}
	removeFilesReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchFileRemover) RemoveFiles(arg1 ...string) error {
	fake.removeFilesMutex.Lock()
	ret, specificReturn := fake.removeFilesReturnsOnCall[len(fake.removeFilesArgsForCall)]
	fake.removeFilesArgsForCall = append(fake.removeFilesArgsForCall, struct {
		arg1 []string
	}{arg1})
	stub := fake.RemoveFilesStub
	fakeReturns := fake.removeFilesReturns
	fake.recordInvocation("RemoveFiles", []interface{}{arg1})
	fake.removeFilesMutex.Unlock()
	if stub != nil {
		return stub(arg1...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchFileRemover) RemoveFilesCallCount() int {
	fake.removeFilesMutex.RLock()
	defer fake.removeFilesMutex.RUnlock()
	return len(fake.removeFilesArgsForCall)
}

func (fake *FakeBatchFileRemover) RemoveFilesCalls(stub func(...string) error) {
	fake.removeFilesMutex.Lock()
	defer fake.removeFilesMutex.Unlock()
	fake.RemoveFilesStub = stub
}

func (fake *FakeBatchFileRemover) RemoveFilesArgsForCall(i int) []string {
	fake.removeFilesMutex.RLock()
	defer fake.removeFilesMutex.RUnlock()
	argsForCall := fake.removeFilesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBatchFileRemover) RemoveFilesReturns(result1 error) {
	fake.removeFilesMutex.Lock()
	defer fake.removeFilesMutex.Unlock()
	fake.RemoveFilesStub = nil
	fake.removeFilesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBatchFileRemover) RemoveFilesReturnsOnCall(i int, result1 error) {
	fake.removeFilesMutex.Lock()
	defer fake.removeFilesMutex.Unlock()
	fake.RemoveFilesStub = nil
	if fake.removeFilesReturnsOnCall == nil {
		fake.removeFilesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeFilesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBatchFileRemover) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.removeFilesMutex.RLock()
	defer fake.removeFilesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchFileRemover) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ writers.BatchFileRemover = new(FakeBatchFileRemover)
