// Code generated by counterfeiter. DO NOT EDIT.
package writersfakes

import (
	"sync"

	"github.com/syntasso/kratix/lib/writers"
)

type FakeGitExecutor struct {
	AddStub        func(...string) (string, error)
	addMutex       sync.RWMutex
	addArgsForCall []struct {
		arg1 []string
	}
	addReturns struct {
		result1 string
		result2 error
	}
	addReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	CheckoutStub        func(string) (string, error)
	checkoutMutex       sync.RWMutex
	checkoutArgsForCall []struct {
		arg1 string
	}
	checkoutReturns struct {
		result1 string
		result2 error
	}
	checkoutReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	CloneStub        func(string) (string, error)
	cloneMutex       sync.RWMutex
	cloneArgsForCall []struct {
		arg1 string
	}
	cloneReturns struct {
		result1 string
		result2 error
	}
	cloneReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	CommitAndPushStub        func(string, string, string, string) (string, error)
	commitAndPushMutex       sync.RWMutex
	commitAndPushArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 string
	}
	commitAndPushReturns struct {
		result1 string
		result2 error
	}
	commitAndPushReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	HasChangesStub        func() (bool, error)
	hasChangesMutex       sync.RWMutex
	hasChangesArgsForCall []struct {
	}
	hasChangesReturns struct {
		result1 bool
		result2 error
	}
	hasChangesReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	PushStub        func(string, bool) (string, error)
	pushMutex       sync.RWMutex
	pushArgsForCall []struct {
		arg1 string
		arg2 bool
	}
	pushReturns struct {
		result1 string
		result2 error
	}
	pushReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	RemoveDirectoryStub        func(string) error
	removeDirectoryMutex       sync.RWMutex
	removeDirectoryArgsForCall []struct {
		arg1 string
	}
	removeDirectoryReturns struct {
		result1 error
	}
	removeDirectoryReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveFileStub        func(string) error
	removeFileMutex       sync.RWMutex
	removeFileArgsForCall []struct {
		arg1 string
	}
	removeFileReturns struct {
		result1 error
	}
	removeFileReturnsOnCall map[int]struct {
		result1 error
	}
	RootStub        func() string
	rootMutex       sync.RWMutex
	rootArgsForCall []struct {
	}
	rootReturns struct {
		result1 string
	}
	rootReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGitExecutor) Add(arg1 ...string) (string, error) {
	fake.addMutex.Lock()
	ret, specificReturn := fake.addReturnsOnCall[len(fake.addArgsForCall)]
	fake.addArgsForCall = append(fake.addArgsForCall, struct {
		arg1 []string
	}{arg1})
	stub := fake.AddStub
	fakeReturns := fake.addReturns
	fake.recordInvocation("Add", []interface{}{arg1})
	fake.addMutex.Unlock()
	if stub != nil {
		return stub(arg1...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitExecutor) AddCallCount() int {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	return len(fake.addArgsForCall)
}

func (fake *FakeGitExecutor) AddCalls(stub func(...string) (string, error)) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = stub
}

func (fake *FakeGitExecutor) AddArgsForCall(i int) []string {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	argsForCall := fake.addArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitExecutor) AddReturns(result1 string, result2 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	fake.addReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) AddReturnsOnCall(i int, result1 string, result2 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	if fake.addReturnsOnCall == nil {
		fake.addReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.addReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) Checkout(arg1 string) (string, error) {
	fake.checkoutMutex.Lock()
	ret, specificReturn := fake.checkoutReturnsOnCall[len(fake.checkoutArgsForCall)]
	fake.checkoutArgsForCall = append(fake.checkoutArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CheckoutStub
	fakeReturns := fake.checkoutReturns
	fake.recordInvocation("Checkout", []interface{}{arg1})
	fake.checkoutMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitExecutor) CheckoutCallCount() int {
	fake.checkoutMutex.RLock()
	defer fake.checkoutMutex.RUnlock()
	return len(fake.checkoutArgsForCall)
}

func (fake *FakeGitExecutor) CheckoutCalls(stub func(string) (string, error)) {
	fake.checkoutMutex.Lock()
	defer fake.checkoutMutex.Unlock()
	fake.CheckoutStub = stub
}

func (fake *FakeGitExecutor) CheckoutArgsForCall(i int) string {
	fake.checkoutMutex.RLock()
	defer fake.checkoutMutex.RUnlock()
	argsForCall := fake.checkoutArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitExecutor) CheckoutReturns(result1 string, result2 error) {
	fake.checkoutMutex.Lock()
	defer fake.checkoutMutex.Unlock()
	fake.CheckoutStub = nil
	fake.checkoutReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) CheckoutReturnsOnCall(i int, result1 string, result2 error) {
	fake.checkoutMutex.Lock()
	defer fake.checkoutMutex.Unlock()
	fake.CheckoutStub = nil
	if fake.checkoutReturnsOnCall == nil {
		fake.checkoutReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.checkoutReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) Clone(arg1 string) (string, error) {
	fake.cloneMutex.Lock()
	ret, specificReturn := fake.cloneReturnsOnCall[len(fake.cloneArgsForCall)]
	fake.cloneArgsForCall = append(fake.cloneArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CloneStub
	fakeReturns := fake.cloneReturns
	fake.recordInvocation("Clone", []interface{}{arg1})
	fake.cloneMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitExecutor) CloneCallCount() int {
	fake.cloneMutex.RLock()
	defer fake.cloneMutex.RUnlock()
	return len(fake.cloneArgsForCall)
}

func (fake *FakeGitExecutor) CloneCalls(stub func(string) (string, error)) {
	fake.cloneMutex.Lock()
	defer fake.cloneMutex.Unlock()
	fake.CloneStub = stub
}

func (fake *FakeGitExecutor) CloneArgsForCall(i int) string {
	fake.cloneMutex.RLock()
	defer fake.cloneMutex.RUnlock()
	argsForCall := fake.cloneArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitExecutor) CloneReturns(result1 string, result2 error) {
	fake.cloneMutex.Lock()
	defer fake.cloneMutex.Unlock()
	fake.CloneStub = nil
	fake.cloneReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) CloneReturnsOnCall(i int, result1 string, result2 error) {
	fake.cloneMutex.Lock()
	defer fake.cloneMutex.Unlock()
	fake.CloneStub = nil
	if fake.cloneReturnsOnCall == nil {
		fake.cloneReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.cloneReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) CommitAndPush(arg1 string, arg2 string, arg3 string, arg4 string) (string, error) {
	fake.commitAndPushMutex.Lock()
	ret, specificReturn := fake.commitAndPushReturnsOnCall[len(fake.commitAndPushArgsForCall)]
	fake.commitAndPushArgsForCall = append(fake.commitAndPushArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.CommitAndPushStub
	fakeReturns := fake.commitAndPushReturns
	fake.recordInvocation("CommitAndPush", []interface{}{arg1, arg2, arg3, arg4})
	fake.commitAndPushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitExecutor) CommitAndPushCallCount() int {
	fake.commitAndPushMutex.RLock()
	defer fake.commitAndPushMutex.RUnlock()
	return len(fake.commitAndPushArgsForCall)
}

func (fake *FakeGitExecutor) CommitAndPushCalls(stub func(string, string, string, string) (string, error)) {
	fake.commitAndPushMutex.Lock()
	defer fake.commitAndPushMutex.Unlock()
	fake.CommitAndPushStub = stub
}

func (fake *FakeGitExecutor) CommitAndPushArgsForCall(i int) (string, string, string, string) {
	fake.commitAndPushMutex.RLock()
	defer fake.commitAndPushMutex.RUnlock()
	argsForCall := fake.commitAndPushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeGitExecutor) CommitAndPushReturns(result1 string, result2 error) {
	fake.commitAndPushMutex.Lock()
	defer fake.commitAndPushMutex.Unlock()
	fake.CommitAndPushStub = nil
	fake.commitAndPushReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) CommitAndPushReturnsOnCall(i int, result1 string, result2 error) {
	fake.commitAndPushMutex.Lock()
	defer fake.commitAndPushMutex.Unlock()
	fake.CommitAndPushStub = nil
	if fake.commitAndPushReturnsOnCall == nil {
		fake.commitAndPushReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.commitAndPushReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) HasChanges() (bool, error) {
	fake.hasChangesMutex.Lock()
	ret, specificReturn := fake.hasChangesReturnsOnCall[len(fake.hasChangesArgsForCall)]
	fake.hasChangesArgsForCall = append(fake.hasChangesArgsForCall, struct {
	}{})
	stub := fake.HasChangesStub
	fakeReturns := fake.hasChangesReturns
	fake.recordInvocation("HasChanges", []interface{}{})
	fake.hasChangesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitExecutor) HasChangesCallCount() int {
	fake.hasChangesMutex.RLock()
	defer fake.hasChangesMutex.RUnlock()
	return len(fake.hasChangesArgsForCall)
}

func (fake *FakeGitExecutor) HasChangesCalls(stub func() (bool, error)) {
	fake.hasChangesMutex.Lock()
	defer fake.hasChangesMutex.Unlock()
	fake.HasChangesStub = stub
}

func (fake *FakeGitExecutor) HasChangesReturns(result1 bool, result2 error) {
	fake.hasChangesMutex.Lock()
	defer fake.hasChangesMutex.Unlock()
	fake.HasChangesStub = nil
	fake.hasChangesReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) HasChangesReturnsOnCall(i int, result1 bool, result2 error) {
	fake.hasChangesMutex.Lock()
	defer fake.hasChangesMutex.Unlock()
	fake.HasChangesStub = nil
	if fake.hasChangesReturnsOnCall == nil {
		fake.hasChangesReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.hasChangesReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) Push(arg1 string, arg2 bool) (string, error) {
	fake.pushMutex.Lock()
	ret, specificReturn := fake.pushReturnsOnCall[len(fake.pushArgsForCall)]
	fake.pushArgsForCall = append(fake.pushArgsForCall, struct {
		arg1 string
		arg2 bool
	}{arg1, arg2})
	stub := fake.PushStub
	fakeReturns := fake.pushReturns
	fake.recordInvocation("Push", []interface{}{arg1, arg2})
	fake.pushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitExecutor) PushCallCount() int {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	return len(fake.pushArgsForCall)
}

func (fake *FakeGitExecutor) PushCalls(stub func(string, bool) (string, error)) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = stub
}

func (fake *FakeGitExecutor) PushArgsForCall(i int) (string, bool) {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	argsForCall := fake.pushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGitExecutor) PushReturns(result1 string, result2 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	fake.pushReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) PushReturnsOnCall(i int, result1 string, result2 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	if fake.pushReturnsOnCall == nil {
		fake.pushReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.pushReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeGitExecutor) RemoveDirectory(arg1 string) error {
	fake.removeDirectoryMutex.Lock()
	ret, specificReturn := fake.removeDirectoryReturnsOnCall[len(fake.removeDirectoryArgsForCall)]
	fake.removeDirectoryArgsForCall = append(fake.removeDirectoryArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.RemoveDirectoryStub
	fakeReturns := fake.removeDirectoryReturns
	fake.recordInvocation("RemoveDirectory", []interface{}{arg1})
	fake.removeDirectoryMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitExecutor) RemoveDirectoryCallCount() int {
	fake.removeDirectoryMutex.RLock()
	defer fake.removeDirectoryMutex.RUnlock()
	return len(fake.removeDirectoryArgsForCall)
}

func (fake *FakeGitExecutor) RemoveDirectoryCalls(stub func(string) error) {
	fake.removeDirectoryMutex.Lock()
	defer fake.removeDirectoryMutex.Unlock()
	fake.RemoveDirectoryStub = stub
}

func (fake *FakeGitExecutor) RemoveDirectoryArgsForCall(i int) string {
	fake.removeDirectoryMutex.RLock()
	defer fake.removeDirectoryMutex.RUnlock()
	argsForCall := fake.removeDirectoryArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitExecutor) RemoveDirectoryReturns(result1 error) {
	fake.removeDirectoryMutex.Lock()
	defer fake.removeDirectoryMutex.Unlock()
	fake.RemoveDirectoryStub = nil
	fake.removeDirectoryReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitExecutor) RemoveDirectoryReturnsOnCall(i int, result1 error) {
	fake.removeDirectoryMutex.Lock()
	defer fake.removeDirectoryMutex.Unlock()
	fake.RemoveDirectoryStub = nil
	if fake.removeDirectoryReturnsOnCall == nil {
		fake.removeDirectoryReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeDirectoryReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitExecutor) RemoveFile(arg1 string) error {
	fake.removeFileMutex.Lock()
	ret, specificReturn := fake.removeFileReturnsOnCall[len(fake.removeFileArgsForCall)]
	fake.removeFileArgsForCall = append(fake.removeFileArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.RemoveFileStub
	fakeReturns := fake.removeFileReturns
	fake.recordInvocation("RemoveFile", []interface{}{arg1})
	fake.removeFileMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitExecutor) RemoveFileCallCount() int {
	fake.removeFileMutex.RLock()
	defer fake.removeFileMutex.RUnlock()
	return len(fake.removeFileArgsForCall)
}

func (fake *FakeGitExecutor) RemoveFileCalls(stub func(string) error) {
	fake.removeFileMutex.Lock()
	defer fake.removeFileMutex.Unlock()
	fake.RemoveFileStub = stub
}

func (fake *FakeGitExecutor) RemoveFileArgsForCall(i int) string {
	fake.removeFileMutex.RLock()
	defer fake.removeFileMutex.RUnlock()
	argsForCall := fake.removeFileArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitExecutor) RemoveFileReturns(result1 error) {
	fake.removeFileMutex.Lock()
	defer fake.removeFileMutex.Unlock()
	fake.RemoveFileStub = nil
	fake.removeFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitExecutor) RemoveFileReturnsOnCall(i int, result1 error) {
	fake.removeFileMutex.Lock()
	defer fake.removeFileMutex.Unlock()
	fake.RemoveFileStub = nil
	if fake.removeFileReturnsOnCall == nil {
		fake.removeFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitExecutor) Root() string {
	fake.rootMutex.Lock()
	ret, specificReturn := fake.rootReturnsOnCall[len(fake.rootArgsForCall)]
	fake.rootArgsForCall = append(fake.rootArgsForCall, struct {
	}{})
	stub := fake.RootStub
	fakeReturns := fake.rootReturns
	fake.recordInvocation("Root", []interface{}{})
	fake.rootMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitExecutor) RootCallCount() int {
	fake.rootMutex.RLock()
	defer fake.rootMutex.RUnlock()
	return len(fake.rootArgsForCall)
}

func (fake *FakeGitExecutor) RootCalls(stub func() string) {
	fake.rootMutex.Lock()
	defer fake.rootMutex.Unlock()
	fake.RootStub = stub
}

func (fake *FakeGitExecutor) RootReturns(result1 string) {
	fake.rootMutex.Lock()
	defer fake.rootMutex.Unlock()
	fake.RootStub = nil
	fake.rootReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGitExecutor) RootReturnsOnCall(i int, result1 string) {
	fake.rootMutex.Lock()
	defer fake.rootMutex.Unlock()
	fake.RootStub = nil
	if fake.rootReturnsOnCall == nil {
		fake.rootReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.rootReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGitExecutor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	fake.checkoutMutex.RLock()
	defer fake.checkoutMutex.RUnlock()
	fake.cloneMutex.RLock()
	defer fake.cloneMutex.RUnlock()
	fake.commitAndPushMutex.RLock()
	defer fake.commitAndPushMutex.RUnlock()
	fake.hasChangesMutex.RLock()
	defer fake.hasChangesMutex.RUnlock()
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	fake.removeDirectoryMutex.RLock()
	defer fake.removeDirectoryMutex.RUnlock()
	fake.removeFileMutex.RLock()
	defer fake.removeFileMutex.RUnlock()
	fake.rootMutex.RLock()
	defer fake.rootMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGitExecutor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ writers.GitExecutor = new(FakeGitExecutor)
