{{- range .Values.stateStores }}
---
apiVersion: platform.kratix.io/v1alpha1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
spec:
  path: {{ .path }}
  secretRef:
    name: {{ .secretRef.name }}
    namespace: {{ .namespace }}
  {{- if eq .kind "GitStateStore" }}
  url: {{ .url }}
  branch: {{ .branch }}
  {{- else }}
  bucketName: {{ .bucket }}
  endpoint: {{ .endpoint }}
  insecure: {{ .insecure }}
  {{- end }}
{{ if .secretRef.values }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretRef.name }}
  namespace: {{ .namespace }}
type: Opaque
data: {{ toYaml .secretRef.values | nindent 2 }}
{{ end }}
{{ end }}
