name: Push Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  make-build-platform-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Build with make target
        run: make docker-build-and-no-push
      - name: Checkout ci repository
        uses: actions/checkout@v3

  make-build-adapter-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Build with make target
        run: make docker-build-and-no-push
      - name: Checkout ci repository
        uses: actions/checkout@v3

  template-build-platform-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: platform-builder
        uses: docker/setup-buildx-action@v3
      - name: Build and no push platform
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: syntasso/kratix-adapter:latest
          builder: kratix-image-builder
          platforms: linux/arm64,linux/amd64
      - name: Build and no push adapter
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: syntasso/kratix-platform:latest
          builder: ${{ steps.platform-builder.outputs.name }}
          platforms: linux/arm64,linux/amd64

  template-build-adapter-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: adapter-builder
        uses: docker/setup-buildx-action@v3
      - name: Build and no push platform
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: syntasso/kratix-adapter:latest
          builder: ${{ steps.adapter-builder.outputs.name }}
          platforms: linux/arm64,linux/amd64
      - name: Build and no push adapter
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: syntasso/kratix-adapter:latest
          builder: work-creator-image-builder
          platforms: linux/arm64,linux/amd64